### ISSUE TITLE
Add tzdata pgk in all image

### ISSUE THREAD

**Issue by jidckii** [jrottenberg/ffmpeg#108]
Hello.
The change of the time zone does not work through the transmission of the environment variable.
```
  archive_stream:
    image: jrottenberg/ffmpeg:4.0-alpine
    container_name: archive_stream
    restart: always
    environment:
      - "TZ=Asia/Yekaterinburg"
```

**Comment by jidckii** [comment]
I'm sorry, but I have very bad English, and I did not understand the answer.
Do you suggest that I create my image based on your own, or will you add this package to the Dockerfile template of your build?
I just do not want to make my fork because of the 1st package.
The tzdata installation does not break anything, by default it will be the same timezone, but this will make it easy to change it by passing env.
As you can understand from the context, this is necessary when creating video archives when the file name is formed relative to the time it was created.
Example:
```
  archive_stream:
    image: jrottenberg/ffmpeg:4.0-alpine
    container_name: archive_stream
    depends_on:
      - in_stream
    networks:
      - poc
    restart: always
      environment:
        - "TZ=Asia/Yekaterinburg"
    volumes:
      - live_files:/live_files
      - archive_files:/tmp/workdir
    command: ' -v 40 -nostats -i /live_files/live.m3u8
              -map 0 -c copy -r 15
              -f segment 
              -segment_atclocktime 1 
              -segment_time 3600
              -strftime 1 
              %Y-%m-%d_%H-%M.mp4'
```
